/*  
    ----------***----------
    Author  : Ajithkumar Madhavankutty
    Company : Sterco Digitex Pvt Ltd
    Email   : ajith.kumar@stercodigitex.com
              ajithmadhav007@gmail.com
    Date    : 12-July-2021
    ----------***----------
*/
(function(){var n={};n.shuffleItems=function(n){for(var i=[],r=!1,t,u;!r;)t=Math.floor(Math.random()*n.length),u=n[t],n.splice(t,1),i.push(u),n.length==0&&(r=!0);return i};n.setLabelText=function(n,t,i,r,u,f){n=setTextStyle(n);var e=new createjs.Text(n,i+"px "+t,r);return e.textAlign=u?u:"left",e.textBaseline=f?f:"top",e};setTextStyle=function(n){return n.split("<br>").join("\n")};n.createInputDomText=function(n,t,i,r,u){var f=document.createElement("input");return f.type=t,f.className=i,f.id=r,f.maxLength=u,f.oninput=function(){this.value.length>this.maxLength&&(this.value=this.value.slice(0,this.maxLength))},n.appendChild(f),document.getElementById(f.id)};n.createDomText=function(n,t,i){var r=document.createElement("div");return r.className=t,r.id=i,n.appendChild(r),document.getElementById(r.id)};n.isMobile=function(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/IEMobile/i)||navigator.userAgent.match(/WPDesktop/i)?!0:navigator.userAgent.toLowerCase().indexOf("windows nt")!=-1&&navigator.userAgent.toLowerCase().indexOf("touch")!=-1?!0:!1};n.isLocalChrome=function(){var n=!1;return!document.location.host&&createjs.BrowserDetect.isChrome&&(n=!0),n};n.checkAppVersion=function(){var r=navigator.appName,t=navigator.userAgent,i,n=t.match(/(opera|chrome|safari|firefox|msie)\/?\s*(\.?\d+(\.\d+)*)/i);return n&&(i=t.match(/version\/([\.\d]+)/i))!=null&&(n[2]=i[1]),n?[n[1],n[2]]:[r,navigator.appVersion,"-?"]};n.deviceName=function(){var n="Unknown";return window.navigator.userAgent.indexOf("Windows")!=-1&&(n="Windows"),window.navigator.userAgent.indexOf("Mac")!=-1&&(n="Mac/iOS"),window.navigator.userAgent.indexOf("X11")!=-1&&(n="UNIX"),window.navigator.userAgent.indexOf("Linux")!=-1&&(n="Linux"),n};window.Utils=n})()